--- 
:anonymous: true
:graphs: 
- host: localhost.localdomain
  plugin: cpu-0
  start: 1375268235
- host: ubuntu.localdomain
  plugin: cpu-0
  start: 1375268235
- host: app-01.example.org
  plugin: cpu-0
  start: 1375268235
:timeframe: true
:id: 5fe7aacef2d355851af1ee78d293e3b6
:created_at: 2013-07-31 23:39:19.208713 +10:00
