---
:anonymous: false
:name: Load on foo, bar, baz
:graphs:
- host: foo
  plugin: load
  start: 1375268235
- host: bar
  plugin: load
  start: 1375268235
- host: baz
  plugin: load
  start: 1375268235
:timeframe: true
:id: 7aacef2d355851af1ee78d293e3b65fe
:created_at: 2013-07-31 23:39:19.208713 +10:00
