---
:anonymous: false
:name: A memory graph
:graphs:
- host: foo
  plugin: memory
  start: 1375268235
:timeframe: true
:id: fffe7aacef2d355851af1ee78d293e3b
:created_at: 2013-07-31 23:39:19.208713 +10:00
