--- 
flapjack+worker+memory: 
  :hosts: flapjack*
  :metrics: memory/*
  :url: flapjack+worker+memory
  :profile_name: flapjack worker memory
flapjack+worker+cpu: 
  :hosts: flapjack*
  :metrics: cpu*/*
  :url: flapjack+worker+cpu
  :profile_name: flapjack worker cpu
